ReasonForNonAttendance.create(motivo: "Contratación a plazo indefinido")
ReasonForNonAttendance.create(motivo: "Retiro")
ReasonForNonAttendance.create(motivo: "Subsidios")
ReasonForNonAttendance.create(motivo: "Permiso sin goce de sueldo")
ReasonForNonAttendance.create(motivo: "Incorporación al lugar de trabajo")
ReasonForNonAttendance.create(motivo: "Accidente del trabajo")
ReasonForNonAttendance.create(motivo: "Contratación a plazo fijo")
ReasonForNonAttendance.create(motivo: "Cambio desde contrato plazo fijo a plazo indefinido")